### ISSUE TITLE
Suggestion: change title color

### ISSUE THREAD

**Issue by Mr-Byron** [emamaria/Github#1]
i think it looks better if the main title is a bit more orange

The styling rule could be changed like this:

```css

h1 {
  color: #e09f2f;
}
```
